#!/bin/bash
#SBATCH --job-name=JOBNAME
#SBATCH --mail-type=END,FAIL           # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=cz489@cornell.edu  # Where to send mail
#SBATCH --nodes=1                      # number of nodes requested
#SBATCH --ntasks=1                     # number of tasks to run in parallel
#SBATCH --cpus-per-task=4             # number of CPUs required for each task
#SBATCH --gres=gpu:1g.10gb:1
#SBATCH --time=16:00:00                # Time limit hrs:min:sec
#SBATCH --output=job_%j.log            # Standard output and error log

pwd; hostname; date
module load cuda/11.5
source /home/fs01/cz489/venv/torch_python3.8/bin/activate

python initialize.py setup.txt
COUNTER=1

while true;
do
    python process_mobo.py setup.txt $COUNTER
    COUNTER=$[$COUNTER +1]
done

date
